package com.example.gudumap

import com.example.gudumap.ml.InputNormalizer
import com.example.gudumap.ml.ModelMetadata
import com.example.gudumap.ml.ModelRunner
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File
import java.io.FileInputStream
import java.security.MessageDigest
import kotlin.math.abs
import kotlin.math.max

/**
 * Deterministic Python <-> Android numerical parity verification for frozen IO-VNBD GRU model.
 *
 * Requirements:
 * - Model: gru_io_vnbd.onnx (SHA-256: 32A512EB668205D2C358FB7D94BE84B24089112A2DC3264D9DCB6E323935FABF)
 * - Normalization: io_vnbd_normalization.json (SHA-256: A0DF903FFAA4FA491992BCDF763A8B99AA8228D1CACEF7167CD91FC9C73831C6)
 * - Deterministic input: Exactly one [1, 20, 6] Float32 tensor with mixed positive/negative values.
 * - End-to-end execution: raw input -> Android validation -> normalization -> ONNX inference -> denormalization.
 * - Strict parity tolerance: |Android - Python| <= 1e-4 meters per component.
 */
class IoVnbdNumericalParityTest {

    companion object {
        const val EXPECTED_ONNX_SHA256 = "32A512EB668205D2C358FB7D94BE84B24089112A2DC3264D9DCB6E323935FABF"
        const val EXPECTED_NORM_SHA256 = "A0DF903FFAA4FA491992BCDF763A8B99AA8228D1CACEF7167CD91FC9C73831C6"

        // Authoritative Python reference displacement output for DETERMINISTIC_INPUT_20X6
        // Computed by authoritative ONNX Runtime in Python with io_vnbd_normalization.json
        val PYTHON_EXPECTED_DISPLACEMENT_METERS = floatArrayOf(
            37.71060944f, // dx (meters)
            0.43085584f,  // dy (meters)
            -0.02406596f  // dz (meters)
        )

        val PYTHON_RAW_ONNX_OUTPUT = floatArrayOf(
            0.66302574f,  // norm_dx
            0.28952680f,  // norm_dy
            -0.02406596f  // norm_dz
        )

        // Exact 20x6 deterministic float32 tensor generated by Python with seed 26168
        val DETERMINISTIC_INPUT_20X6: Array<FloatArray> = arrayOf(
            floatArrayOf(-0.02001521f, -0.19177397f, 0.15784672f, -0.11974997f, 0.02082411f, -0.00849771f),
            floatArrayOf(-0.10632973f, 0.21231312f, 0.22656564f, -0.05583314f, -0.13030134f, -0.06852483f),
            floatArrayOf(-0.15863156f, 0.07639108f, 0.13623047f, -0.12087952f, 0.05218431f, 0.13516752f),
            floatArrayOf(0.24022245f, 0.13163304f, 0.18486631f, -0.14947513f, 0.04874323f, -0.07253262f),
            floatArrayOf(-0.02917440f, -0.21776460f, -0.00933903f, 0.03669180f, -0.12709035f, 0.06991491f),
            floatArrayOf(-0.10083226f, -0.09826870f, 0.01663597f, 0.11006437f, 0.14662842f, 0.07609451f),
            floatArrayOf(-0.11775196f, 0.19455205f, 0.08322118f, -0.09935110f, 0.07163589f, 0.05076969f),
            floatArrayOf(0.09057108f, -0.24433441f, 0.01153591f, -0.00643142f, 0.10797697f, 0.00557432f),
            floatArrayOf(-0.22829443f, -0.09546366f, 0.13770884f, 0.01122162f, -0.01154773f, -0.11176836f),
            floatArrayOf(-0.14186342f, 0.05157206f, 0.13697979f, 0.11278450f, -0.09601977f, -0.11486706f),
            floatArrayOf(-0.04862218f, 0.13204668f, 0.13843271f, -0.06442346f, -0.13955772f, -0.02652203f),
            floatArrayOf(-0.07276939f, 0.18352002f, 0.00802500f, 0.10251176f, -0.00077807f, 0.11345904f),
            floatArrayOf(-0.16459765f, 0.18383215f, 0.15208575f, 0.01719732f, -0.06873534f, 0.11941458f),
            floatArrayOf(0.07816719f, 0.17547023f, -0.21600601f, 0.02817868f, -0.13712522f, -0.05135822f),
            floatArrayOf(-0.19857615f, 0.02800648f, 0.20305941f, 0.10850461f, 0.06713021f, 0.10958745f),
            floatArrayOf(-0.05091212f, -0.21713686f, -0.09319700f, 0.08268289f, -0.05432664f, -0.01085545f),
            floatArrayOf(0.24648535f, -0.23183730f, -0.06139821f, -0.11258636f, -0.04749970f, 0.05591056f),
            floatArrayOf(-0.01895541f, 0.14555362f, 0.14099762f, 0.14897019f, -0.02514830f, -0.05872535f),
            floatArrayOf(-0.20314665f, 0.01171217f, 0.11773120f, -0.06076762f, 0.09832321f, -0.03585888f),
            floatArrayOf(0.20343283f, 0.03522857f, 0.13335562f, 0.01597587f, -0.03982694f, 0.05563973f)
        )
    }

    private fun findModelFile(): File {
        val candidates = listOf(
            File("src/main/assets/gru_io_vnbd.onnx"),
            File("app/src/main/assets/gru_io_vnbd.onnx"),
            File("../app/src/main/assets/gru_io_vnbd.onnx"),
            File("../../../../models/frozen_io_vnbd/gru_io_vnbd.onnx"),
            File("d:/dead_reckoning/models/frozen_io_vnbd/gru_io_vnbd.onnx"),
            File("d:/dead_reckoning/FE/gudumap/gudumap/app/src/main/assets/gru_io_vnbd.onnx")
        )
        return candidates.firstOrNull { it.exists() && it.length() > 0 }
            ?: throw IllegalStateException("gru_io_vnbd.onnx not found in search paths")
    }

    private fun findNormalizationFile(): File {
        val candidates = listOf(
            File("src/main/assets/io_vnbd_normalization.json"),
            File("app/src/main/assets/io_vnbd_normalization.json"),
            File("../app/src/main/assets/io_vnbd_normalization.json"),
            File("../../../../models/frozen_io_vnbd/io_vnbd_normalization.json"),
            File("d:/dead_reckoning/models/frozen_io_vnbd/io_vnbd_normalization.json"),
            File("d:/dead_reckoning/FE/gudumap/gudumap/app/src/main/assets/io_vnbd_normalization.json")
        )
        return candidates.firstOrNull { it.exists() && it.length() > 0 }
            ?: throw IllegalStateException("io_vnbd_normalization.json not found in search paths")
    }

    private fun computeSha256(file: File): String {
        val md = MessageDigest.getInstance("SHA-256")
        FileInputStream(file).use { fis ->
            val buffer = ByteArray(8192)
            var n: Int
            while (fis.read(buffer).also { n = it } != -1) {
                md.update(buffer, 0, n)
            }
        }
        return md.digest().joinToString("") { "%02X".format(it) }
    }

    @Test
    fun testAssetIntegrityAndExactSha256() {
        val modelFile = findModelFile()
        val normFile = findNormalizationFile()

        val modelHash = computeSha256(modelFile)
        val normHash = computeSha256(normFile)

        assertEquals("ONNX model SHA-256 must match frozen artifact exactly", EXPECTED_ONNX_SHA256, modelHash)
        assertEquals("Normalization JSON SHA-256 must match frozen artifact exactly", EXPECTED_NORM_SHA256, normHash)
    }

    @Test
    fun testDeterministicPythonAndroidNumericalParity() {
        val modelFile = findModelFile()
        val normFile = findNormalizationFile()

        // 1. Load normalization from asset stream
        val params = FileInputStream(normFile).use { stream ->
            ModelMetadata.loadNormalizationFromStream(stream)
        }

        // Verify loaded parameters match defaults
        assertEquals(26.469011f, params.targetMean[0], 1e-4f)
        assertEquals(0.019715862f, params.targetMean[1], 1e-5f)
        assertEquals(0.0f, params.targetMean[2], 1e-6f)
        assertEquals(16.954994f, params.targetStd[0], 1e-4f)
        assertEquals(1.4200412f, params.targetStd[1], 1e-5f)
        assertEquals(1.0f, params.targetStd[2], 1e-6f)

        // 2. Initialize normalizer and ModelRunner with loaded parameters
        val normalizer = InputNormalizer(params)
        val runner = ModelRunner(normalizer)

        FileInputStream(modelFile).use { stream ->
            runner.initializeFromStream(stream)
        }

        assertTrue("ModelRunner must be ready after loading gru_io_vnbd.onnx", runner.ready)

        // 3. Execute Android production inference path
        val actualDisplacement = runner.predict(DETERMINISTIC_INPUT_20X6)

        assertNotNull(actualDisplacement)
        assertEquals(3, actualDisplacement.size)

        // 4. Component-wise difference comparison with strict tolerance <= 1e-4 m (0.1 mm)
        val diffDx = abs(actualDisplacement[0] - PYTHON_EXPECTED_DISPLACEMENT_METERS[0])
        val diffDy = abs(actualDisplacement[1] - PYTHON_EXPECTED_DISPLACEMENT_METERS[1])
        val diffDz = abs(actualDisplacement[2] - PYTHON_EXPECTED_DISPLACEMENT_METERS[2])
        val maxDiff = max(diffDx, max(diffDy, diffDz))

        println("=".repeat(60))
        println("NUMERICAL PARITY RESULTS:")
        println("Python Expected: [dx=${PYTHON_EXPECTED_DISPLACEMENT_METERS[0]}, dy=${PYTHON_EXPECTED_DISPLACEMENT_METERS[1]}, dz=${PYTHON_EXPECTED_DISPLACEMENT_METERS[2]}] m")
        println("Android Actual : [dx=${actualDisplacement[0]}, dy=${actualDisplacement[1]}, dz=${actualDisplacement[2]}] m")
        println("Abs Differences: [dx=$diffDx, dy=$diffDy, dz=$diffDz] m")
        println("Max Abs Diff   : $maxDiff m")
        println("=".repeat(60))

        val tolerance = 1e-4f // 0.1 mm
        assertTrue("dx diff ($diffDx m) exceeds tolerance ($tolerance m)", diffDx <= tolerance)
        assertTrue("dy diff ($diffDy m) exceeds tolerance ($tolerance m)", diffDy <= tolerance)
        assertTrue("dz diff ($diffDz m) exceeds tolerance ($tolerance m)", diffDz <= tolerance)
        assertTrue("Max diff ($maxDiff m) exceeds tolerance ($tolerance m)", maxDiff <= tolerance)

        runner.close()
    }

    @Test
    fun testRejectionOfWrongShapeAndInvalidValues() {
        val normalizer = InputNormalizer()

        // 1. Wrong shape (19 samples instead of 20)
        val shortWindow = Array(19) { FloatArray(6) }
        try {
            normalizer.validateWindow(shortWindow)
            fail("Expected IllegalArgumentException for 19 samples")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!.contains("Invalid window size"))
        }

        // 2. Wrong feature count (5 instead of 6)
        val wrongFeatures = Array(20) { FloatArray(5) }
        try {
            normalizer.validateWindow(wrongFeatures)
            fail("Expected IllegalArgumentException for 5 features")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!.contains("Invalid feature count"))
        }

        // 3. Non-finite values
        val nanWindow = Array(20) { FloatArray(6) }
        nanWindow[10][3] = Float.NaN
        try {
            normalizer.validateWindow(nanWindow)
            fail("Expected IllegalArgumentException for NaN")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!.contains("non-finite"))
        }
    }
}
