"""FastAPI app for SIH26168 -- Smartphone-Only GNSS-Blackout Dead Reckoning.

DEPRECATED -- NOT PART OF THE SHIPPED PRODUCT (as of 2026-09-05).
The shipped system (`gudumap/`) runs ML inference, EKF fusion, and ZUPT
entirely on-device on Android -- there is no backend in the product, and
there never needs to be one, since the whole point is working through a
GNSS blackout with no connectivity. This service predates that decision
and was always mock data anyway (see services/pipeline.py). It is kept
only because its evaluation code is still useful for offline scoring, not
as a running service. See docs/PROJECT_STATUS.md for the current
architecture. Do not present this as a live/product component to a judge.

Run from this directory: `uvicorn main:app --reload`
Docs: http://127.0.0.1:8000/docs (Swagger) or /redoc
Raw spec: http://127.0.0.1:8000/openapi.json (also exported to openapi.json
via `python scripts/generate_openapi.py`, for teammates who'd rather import
a static file into Postman/Insomnia than run the server).

Baseline/corrected/uncertainty are mock data right now (see
services/pipeline.py's module docstring) so the Android client can be built
against a stable contract while physics-baseline/ and ml-residual/ finish.
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

import db
from routers import evaluation, ingest, trajectory

app = FastAPI(
    title="SIH26168 Dead Reckoning API",
    description=(
        "Smartphone-only GNSS-blackout dead reckoning: ingest a raw IMU(+GPS) "
        "trace, then fetch the naive strapdown/ZUPT baseline trajectory, the "
        "ML-residual-corrected trajectory, its duration-bucketed confidence "
        "radius, and headline evaluation metrics (ATE/RTE/CEP/drift-rate).\n\n"
        "**Baseline, corrected, and uncertainty are currently mock data** -- "
        "deterministic per trace, stable across repeated calls, generated by "
        "`backend/services/pipeline.py` -- while `physics-baseline/` and "
        "`ml-residual/` are still in development. Every response's `source` "
        "field says which pipeline produced it, so client code can rely on "
        "that field rather than tracking the swap-over out of band."
    ),
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def _startup() -> None:
    db.init_db()


@app.get("/health", tags=["meta"], summary="Liveness check")
def health() -> dict:
    return {"status": "ok"}


app.include_router(ingest.router)
app.include_router(trajectory.router)
app.include_router(evaluation.router)
